name: merge dev to test

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Unit Tests
      run: |
        python -m unittest test - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Merge to Test Branch
        if: github.ref == 'refs/heads/dev' && success()
        uses: repo-sync/pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          destinationBranch: 'test'.py
          
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Merge to Test Branch
        if: github.ref == 'refs/heads/dev' && success()
        uses: repo-sync/pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          destinationBranch: 'test'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Automated merge dev into test"
        pr_body: "Running unit tests passed, merging branch."
        destination_branch: "test"
        source_branch: "dev"
