name: Create Pull Request on Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated Pull Request from Dev to Test"
          branch: test
          title: "Automated Pull Request from Dev to Test"
          body: "This pull request was automatically created when code was pushed to the dev branch."
          labels: "automated"
          reviewers: "admin-username"
