name: Merge Dev to Test and Test Automation

on:
  push:
    branches:
      - dev

jobs:
  merge-test-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Merge dev into test
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Merge dev into test
          title: Merge dev into test
          base: test
          branch: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install  # Replace with the appropriate command to install dependencies

      - name: Checkout test branch
        run: git checkout test

      - name: Run tests
        run: |
          python test.py
